<div style="margin-left: 10%;margin-right: 10%; margin-top: 5%; font-size: 20px;">
    <p><b style="font-size: 25px;">Conditions générales d'utilisation</b></p>
    <p>
      Les présentes conditions générales d’utilisation, qui sont susceptibles d’être modifiées de façon ponctuelle, s’appliquent à tous nos services, directement ou indirectement (fournis par nos distributeurs) en ligne, via des appareils mobiles, par e-mail ou par téléphone. En accédant à notre site Internet ou à toute autre application via une plateforme, et/ou en y effectuant une réservation, vous déclarez avoir pris connaissance des présentes conditions générales d’utilisation et de notre charte de confidentialité, en comprendre la portée et les accepter.<br><br>
      <b>Permis de conduire</b><br> Chaque conducteur doit posséder un permis de conduire définitif en cours de validité délivré depuis au moins 1 an (2 ans dans certains lieux de location ; ceci sera confirmé au cours du processus de réservation). Les permis expirés ou provisoires ne seront pas acceptés.Notre Centre de réservations doit être informé de toute contravention ou de tout retrait de points affectant la validité de votre permis lors de la réservation ; nous nous réservons le droit de refuser la réservation pour cette raison, conformément aux conditions générales des sociétés de location de voitures avec lesquelles nous travaillons.<br><br>
     <b>Problèmes mécaniques / Accidents</b><br>En cas de panne ou de problèmes mécaniques, vous devez immédiatement appeler la société de location de voitures. La société de location de voitures devra donner l'autorisation pour toute réparation ou tout remplacement de véhicule. Si vous êtes impliqué dans un accident, la police locale et la société de location de voitures doivent être contactées. Veuillez conserver les copies de tous les documents pertinents que l'on vous demande de compléter. Vous pourriez en avoir besoin si vous souhaitez déclarer un sinistre.<br><br>
     <b>Fourniture des voitures</b><br>Kangam_Automobile se réserve le droit de refuser de fournir une voiture à toute personne considérée inapte à la conduite ou ne remplissant pas les conditions requises. Nous ne pourrons être tenus responsables de l’organisation de votre voyage, de tout remboursement ou dédommagement ou d’autres frais que vous pourriez avoir à payer dans un tel cas<br><br>
     <b>Protection des données</b><br>La protection de votre vie privée est importante à nos yeux. En utilisant ce site vous acceptez les conditions de notre avis de confidentialité.<br>Nous pourrions utiliser des cookies ainsi que d’autres technologies afin de faciliter et de suivre votre utilisation des services proposés sur ce site web et dans le cadre de nos communications par email. Pour en savoir plus à ce sujet, consultez notre politique de confidentialité et utilisations des cookies.
    </p>
</div>
