<div style="margin-left: 10%;margin-right: 10%; margin-top: 5%; font-size: 20px;">
    <p><b style="font-size: 25px;">Politique de confidentialité</b></p>
    <p>
    Cette politique de confidentialité explique comment nous collectons, utilisons et protégeons toute information vous concernant. Il vous indique également comment nous contacter si vous avez des questions à son sujet, questions auxquelles nous serons plus qu'heureux de répondre. Si vous êtes intéressé(e) de savoir ce que nous faisons avec les cookies et d'autres technologies similaires, consultez la utilisations des cookies.<br>
    Il se peut que nous apportions des modifications à cette politique de temps en temps ; alors veuillez consulter cette page pour y trouver une éventuelle mise à jour.
    Nous proposons une gamme de services liés à la location de voitures en ligne, via notre propre site web, e-mails et messages texte . Cet politique s'applique à toutes les données d'ordre personnel que nous collectons dans ces circonstances, ou lorsque vous nous contactez par e-mail, chat, téléphone ou courrier.<br><br>
    Nous pouvons utiliser les données à votre sujet de la manière suivante :<br>
    ° <b>Réservations :</b> Tout d'abord, nous utilisons vos données à caractère personnel pour effectuer et gérer votre réservation, et transmettre les informations nécessaires à l'entreprise qui fournit votre voiture. Cela comprend l'envoi de communications relatives à votre réservation, telles que des confirmations, des modifications et des rappels.<br>
    ° <b>Service à la clientèle :</b> Notre service à la clientèle est à votre écoute 24/7. Nos équipes de service client ont besoin de vos coordonnées pour vous aider à faire une réservation, par exemple, ou pour répondre à vos questions avant, pendant ou après votre réservation.<br>
    ° <b>Avis clients :</b> Nous pouvons utiliser vos coordonnées pour vous envoyer un court questionnaire sur votre réservation. Cela nous aide à comprendre et à améliorer nos services .<br>
    ° <b>Service de compte :</b> Pour vous faciliter les choses, vous pouvez créer un compte utilisateur sur la plateforme. Cela implique de nous confier des données vous identifiant, et cela vous permet de faire un certain nombre de choses utiles. Vous pourrez ainsi gérer vos réservations, profiter des offres spéciales et gérer vos paramètres et préférences personnels. Cela facilite également vos futures réservations, qui seront plus rapides car pré-remplies.<br>
    ° <b>Détection et prévention des fraudes :</b> Pour vous fournir un service sûr et fiable, nous utilisons les données vous concernant pour détecter et prévenir la fraude et d’autres activités illégales ou indésirables. De même, nous pouvons utiliser des données d’ordre personnel à des fins d'évaluation des risques et de sécurité, ce qui peut inclure la vérification des utilisateurs et des réservations. Cela peut parfois signifier que nous devrons mettre certaines réservations en attente.<br><br>
    Kangam Automobile est le responsable du traitement des données à caractère personnel sur sa plateforme. Pour toute question, préoccupation, observation ou plainte concernant nos pratiques ou la présente Déclaration de confidentialité, veuillez nous contacter par courriel à l'adresse Kangam_Automobile1@gmail.com , en indiquant « Confidentialité » dans l’objet. Nous vous répondrons dans les meilleurs délais.
    </p>
</div>